// get movie
export const GET_MOVIE_REQUEST = 'GET_MOVIE_REQUEST';
export const GET_MOVIE_LOADING = 'GET_MOVIE_LOADING';
export const GET_MOVIE_REFRESH_LOADING = 'GET_MOVIE_REFRESH_LOADING';
export const GET_MOVIE_SUCCESS = 'GET_MOVIE_SUCCESS';
export const GET_MOVIE_MORE_LOADING = 'GET_MOVIE_MORE_LOADING';
export const GET_MOVIE_MORE_SUCCESS = 'GET_MOVIE_MORE_SUCCESS';
export const GET_MOVIE_FAILED = 'GET_MOVIE_FAILED';

// search movie
export const SEARCH_MOVIE_REQUEST = 'SEARCH_MOVIE_REQUEST';
export const SEARCH_MOVIE_LOADING = 'SEARCH_MOVIE_LOADING';
export const SEARCH_MOVIE_SUCCESS = 'SEARCH_MOVIE_SUCCESS';
export const SEARCH_MOVIE_FAILED = 'SEARCH_MOVIE_FAILED';

// check user login
export const CHECK_LOGIN_USER = 'CHECK_LOGIN_USER';

// Logout
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT = 'LOGOUT';